apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: azure-default-providerconfig-2
spec:
  credentials: |-
    {
      "source": "Secret",
      "secretRef": {
        "namespace": "crossplane-management-showcase-crossplane",
        "name": "azure-providerconfig-credentials",
        "key": "creds"
      }
    }
